<?php if (!defined('__TYPECHO_ROOT_DIR__')) { exit; } ?>
<?php $curveViews = curve_record_view($this); ?>
<?php $curveEditUrl = ''; if ($this->user->hasLogin()) { ob_start(); $this->options->adminUrl('write-post.php?cid=' . (int) $this->cid); $curveEditUrl = trim(ob_get_clean()); } ?>
<?php $this->need('header.php'); ?>
<main class="mian-layout is-post">
    <div class="post">
        <div class="post-meta">
            <div class="meta"><div class="categories"><?php foreach ((array) $this->categories as $category): ?><a class="cat-item" href="<?php echo curve_esc($category['permalink']); ?>"><i class="iconfont icon-folder"></i><span class="name"><?php echo curve_esc($category['name']); ?></span></a><?php endforeach; ?></div><div class="tags"><?php foreach ((array) $this->tags as $tag): ?><a class="tag-item" href="<?php echo curve_esc($tag['permalink']); ?>"><i class="iconfont icon-hashtag"></i><span class="name"><?php echo curve_esc($tag['name']); ?></span></a><?php endforeach; ?></div></div>
            <h1 class="title"><?php $this->title(); ?></h1>
            <div class="other-meta"><span class="meta date"><i class="iconfont icon-date"></i><?php $this->date('Y-m-d'); ?></span><span class="update meta"><i class="iconfont icon-time"></i><?php echo date('Y-m-d', (int) $this->modified); ?></span><span class="hot meta"><i class="iconfont icon-fire"></i><span><?php echo (int) $curveViews; ?></span></span><a class="chat meta hover" href="#main-comment"><i class="iconfont icon-chat"></i><span><?php $this->commentsNum('0', '1', '%d'); ?></span></a><?php if ($curveEditUrl !== ''): ?><a class="edit-post meta hover" href="<?php echo curve_esc($curveEditUrl); ?>" title="编辑文章" aria-label="编辑文章"><i class="iconfont icon-tools"></i><span>编辑文章</span></a><?php endif; ?></div>
        </div>
        <div class="post-content">
            <article class="post-article s-card">
                <?php $expired = (int) floor((time() - (int) $this->created) / 86400); if ($expired >= 180): ?><div class="expired s-card">本文发表于 <strong><?php echo $expired; ?></strong> 天前，其中的信息可能已经事过境迁</div><?php endif; ?>
                <?php $summary = curve_post_field($this, 'description'); $fakeGptEnabled = curve_is_enabled($this->options, 'fakeGptEnable', true); if ($fakeGptEnabled && $summary !== ''): $fakeGptReportUrl = curve_safe_http_url(curve_option($this->options, 'reportUrl')); $fakeGptClickText = curve_option($this->options, 'fakeGptClickText', '你好，我是 FakeGPT：名字听起来很懂，实际上只负责把作者认真写好的摘要一个字一个字端上来。没有联网、没有偷看正文，也没有在后台煮咖啡；这段内容由作者亲自审核，放心食用。'); ?><div class="article-gpt s-card" data-fake-gpt data-fake-gpt-summary="<?php echo curve_esc($summary); ?>" data-fake-gpt-introduction="<?php echo curve_esc($fakeGptClickText); ?>"><div class="title"><span class="name"><i class="iconfont icon-robot"></i>文章摘要<i class="iconfont icon-up"></i></span><span class="logo fake-gpt-loading" data-fake-gpt-toggle role="button" tabindex="0" aria-label="切换 FakeGPT 摘要">FakeGPT</span></div><div class="content s-card"><span class="text" data-fake-gpt-text>加载中...</span><span class="point" data-fake-gpt-point>|</span></div><div class="meta"><span class="tip">此内容根据文章生成，并经过人工审核，仅用于文章内容的解释与总结</span><?php if ($fakeGptReportUrl !== ''): ?><a class="report" href="<?php echo curve_esc($fakeGptReportUrl); ?>" target="_blank" rel="noopener">投诉</a><?php endif; ?></div></div><?php endif; ?>
                <?php ob_start(); $this->content(); $postContent = ob_get_clean(); $curveRenderedContent = curve_render_markdown($postContent); $curveRenderedContent = curve_apply_article_link_target($curveRenderedContent, curve_article_link_target($this->options)); $curveHasMath = preg_match('/(?:\$\$|(?<!\$)\$[^$\n]+\$)/u', $postContent); if (strpos($curveRenderedContent, 'math-inline') !== false || strpos($curveRenderedContent, 'math-block') !== false || $curveHasMath): ?><script>window.MathJax={tex:{inlineMath:[['\\(','\\)'],['$','$']],displayMath:[['\\[','\\]'],['$$','$$']]},options:{skipHtmlTags:['script','noscript','style','textarea','pre','code']}};</script><script defer src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script><?php endif; ?><div id="page-content" class="markdown-main-style" data-article-content><?php echo $curveRenderedContent; ?></div><span data-next-post-trigger aria-hidden="true"></span>
                <?php $references = curve_link_rows(curve_post_field($this, 'references')); if (!empty($references)): ?><div class="references s-card"><div class="title"><i class="iconfont icon-quote"></i><span class="title-text">参考资料</span></div><ul class="list"><?php foreach ($references as $reference): ?><li><a href="<?php echo curve_esc($reference['url']); ?>" class="list-item" target="_blank" rel="noopener"><span class="item-title"><?php echo curve_esc($reference['name']); ?></span></a></li><?php endforeach; ?></ul></div><?php endif; ?>
                <?php $copyrightCreated = curve_format_timestamp((int) $this->created); $copyrightModified = curve_format_timestamp((int) $this->modified); if (curve_is_enabled($this->options, 'showCopyright') && curve_post_field($this, 'copyright', '1') !== '0'): ?><div class="copyright s-card"><div class="title"><span class="post-name"><?php $this->title(); ?></span><a href="<?php $this->permalink(); ?>" class="post-link" target="_blank" rel="noopener"><?php $this->permalink(); ?></a></div><div class="post-meta"><div class="meta-item"><span class="tip">作者</span><span class="name"><?php $this->author(); ?></span></div><div class="meta-item"><span class="tip">发布于</span><span class="name"><?php echo curve_esc($copyrightCreated); ?></span></div><div class="meta-item"><span class="tip">更新于</span><span class="name"><?php echo curve_esc($copyrightModified); ?></span></div><div class="meta-item cc"><span class="tip">许可协议</span><a class="name" href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh-hans" target="_blank" rel="noopener">CC BY-NC-SA 4.0</a></div></div><span class="meta-tip">署名-非商业性使用-相同方式共享 4.0 国际</span></div><?php endif; ?>
                <?php $reportUrl = curve_safe_http_url(curve_option($this->options, 'reportUrl')); ?><div class="other-meta"><div class="all-tags"><?php foreach ((array) $this->tags as $tag): ?><a class="tag-item" href="<?php echo curve_esc($tag['permalink']); ?>"><span class="name"><?php echo curve_esc($tag['name']); ?></span></a><?php endforeach; ?></div><?php if ($reportUrl !== ''): ?><a href="<?php echo curve_esc($reportUrl); ?>" class="report" target="_blank" rel="noopener"><i class="iconfont icon-report"></i>反馈与投诉</a><?php endif; ?></div>
                <?php $wechat = curve_safe_asset_url(curve_option($this->options, 'rewardWechat')); $alipay = curve_safe_asset_url(curve_option($this->options, 'rewardAlipay')); if ($wechat !== '' || $alipay !== ''): ?><div class="reward"><button type="button" class="reward-btn" data-reward-open><i class="iconfont icon-reward"></i><span class="text">赞赏博主</span></button><div class="modal reward-modal" hidden data-reward-modal><div class="modal-mask" data-reward-close></div><div class="modal-main reward-modal-main s-card"><div class="title"><div class="title-left"><i class="iconfont icon-reward"></i><span>赞赏博主</span></div><button type="button" class="close" data-reward-close><i class="iconfont icon-close"></i></button></div><div class="modal-content"><div class="reward-card"><span class="thank">🙏 感谢您赐予我前进的力量</span><div class="qr"><?php if ($wechat !== ''): ?><div class="qr-img"><img src="<?php echo curve_esc($wechat); ?>" alt="微信"><span class="tip wechat"><i class="iconfont icon-wechat-pay"></i>微信</span></div><?php endif; ?><?php if ($alipay !== ''): ?><div class="qr-img"><img src="<?php echo curve_esc($alipay); ?>" alt="支付宝"><span class="tip alipay"><i class="iconfont icon-alipay"></i>支付宝</span></div><?php endif; ?></div></div></div></div></div></div><?php endif; ?>
                <div class="next-post s-card" data-next-post><span class="post-tip">下一篇阅读</span><span class="post-title"><?php $this->theNext('%s', '已经是最后一篇了'); ?></span></div>
                <?php if (curve_is_enabled($this->options, 'relatedEnable', true)): ?><?php $this->related(2)->to($relatedPosts); if ($relatedPosts->have()): ?><div class="related-post"><div class="title"><span class="name"><i class="iconfont icon-star"></i>相关推荐</span><span class="shuffle" data-related-random>随便逛逛</span></div><div class="post-lists"><?php while ($relatedPosts->next()): $relatedDescription = curve_post_field($relatedPosts, 'description'); ?><div class="post-item s-card hover simple"><div class="post-content"><a class="post-title" data-post-link="<?php $relatedPosts->permalink(); ?>" href="<?php $relatedPosts->permalink(); ?>"><?php $relatedPosts->title(); ?></a><?php if ($relatedDescription !== ''): ?><span class="post-desc"><?php echo curve_esc($relatedDescription); ?></span><?php endif; ?></div></div><?php endwhile; ?></div></div><?php endif; ?><?php endif; ?>
                <?php $this->need('comments.php'); ?>
            </article>
            <?php $this->need('sidebar.php'); ?>
        </div>
    </div>
<?php $this->need('footer.php'); ?>
