<?php if (!defined('__TYPECHO_ROOT_DIR__')) { exit; } ?>
<?php $tagsUrl = curve_page_url('page-tags.php'); ?>
<aside class="main-aside">
    <div class="hello s-card weidgets" data-hello-card>
        <span class="tip" data-hello>你好，很高兴见到你</span>
        <div class="content"><div class="site-logo"><div class="clock" data-clock><div class="clock-content"><div class="pointer hour"></div><div class="pointer minute"></div><div class="pointer second"></div></div></div></div><span class="site-desc"><?php echo nl2br(curve_esc(curve_option($this->options, 'intro', '记录值得分享的技术、想法与生活。'))); ?></span></div>
        <div class="info"><div class="name"><span class="author"><?php echo curve_esc(curve_option($this->options, 'siteAuthorName', '鱼鱼')); ?></span><span class="desc"><?php echo nl2br(curve_esc(curve_option($this->options, 'sidebarAuthorDescription', '分享技术生活'))); ?></span></div><div class="link">
            <?php $socialLinks = curve_link_rows(curve_option($this->options, 'socialLinks'), true); if (empty($socialLinks)) { $authorLink = curve_safe_http_url(curve_option($this->options, 'siteAuthorLink')); $authorEmail = curve_option($this->options, 'siteAuthorEmail'); if ($authorLink !== '' && $authorLink !== $this->options->siteUrl) $socialLinks[] = array('name' => 'GitHub', 'url' => $authorLink); if ($authorEmail !== '') $socialLinks[] = array('name' => 'Email', 'url' => 'mailto:' . $authorEmail); } $sidebarSocialLinks = curve_pick_social_links($socialLinks, curve_option($this->options, 'sidebarSocialLinks'), 2); foreach ($sidebarSocialLinks as $social): ?><?php $socialIcon = curve_social_icon_for_link($social); ?><a href="<?php echo curve_esc($social['url']); ?>" class="social-link" target="_blank" rel="noopener" title="<?php echo curve_esc($social['name']); ?>" aria-label="<?php echo curve_esc($social['name']); ?>"><?php if ($socialIcon === 'twitter'): ?><span class="social-mark social-mark-twitter" aria-hidden="true">𝕏</span><?php else: ?><i class="iconfont icon-<?php echo curve_esc($socialIcon); ?>" aria-hidden="true"></i><?php endif; ?></a><?php endforeach; ?>
        </div></div>
    </div>
    <div class="sticky">
        <?php if ($this->is('post') && curve_is_enabled($this->options, 'showToc')): ?><div class="toc s-card weidgets"><div class="toc-title"><i class="iconfont icon-toc"></i><span class="name">目录</span></div><div id="toc-all" class="toc-list" data-toc></div></div><?php endif; ?>
        <?php $countdownName = curve_option($this->options, 'countdownName'); $countdownDate = curve_option($this->options, 'countdownDate'); if ($countdownName !== '' && $countdownDate !== ''): ?><div class="count-down s-card weidgets" data-countdown data-date="<?php echo curve_esc($countdownDate); ?>"><div class="count-left"><span class="text">距离</span><span class="name"><?php echo curve_esc($countdownName); ?></span><span class="time" data-countdown-value>--</span><span class="date"><?php echo curve_esc($countdownDate); ?></span></div><div class="count-right"><?php foreach (array('day' => array('今日', '小时'), 'week' => array('本周', '天'), 'month' => array('本月', '天'), 'year' => array('本年', '天')) as $unit => $labels): ?><div class="count-item" data-countdown-item="<?php echo $unit; ?>"><div class="item-name"><?php echo $labels[0]; ?></div><div class="item-progress"><div class="progress-bar" data-countdown-bar></div><span class="percentage" data-countdown-percent>--%</span><span class="remaining"><span class="tip">还剩</span><span data-countdown-remaining>--</span><span class="tip"><?php echo $labels[1]; ?></span></span></div></div><?php endforeach; ?></div></div><?php endif; ?>
        <div class="tags-cloud s-card weidgets"><div class="title"><i class="iconfont icon-hashtag"></i><span class="title-name">热门标签</span></div><div class="all-tags"><?php $tags = $this->widget('Widget_Metas_Tag_Cloud', 'sort=count&desc=1&limit=1000'); $tagTotal = 0; if ($tags->have()): while ($tags->next()): $tagTotal++; ?><a href="<?php $tags->permalink(); ?>" class="tags"><span class="name"><?php $tags->name(); ?></span><sup class="num"><?php $tags->count(); ?></sup></a><?php endwhile; endif; ?></div><?php if ($tagTotal > 20 && $tagsUrl !== ''): ?><a href="<?php echo curve_esc($tagsUrl); ?>" class="more-tags">查看全部</a><?php endif; ?></div>
        <div class="site-data s-card weidgets"><div class="title"><i class="iconfont icon-chart"></i><span class="title-name">站点数据</span></div><div class="all-data"><?php $stat = $this->widget('Widget_Stat'); ?><div class="data-item"><span class="name"><i class="iconfont icon-article"></i>文章总数</span><span class="num"><?php echo (int) $stat->publishedPostsNum; ?> 篇</span></div><div class="data-item"><span class="name"><i class="iconfont icon-chat"></i>评论总数</span><span class="num"><?php echo (int) $stat->publishedCommentsNum; ?> 条</span></div><?php $days = curve_since_days($this->options); if ($days !== null): ?><div class="data-item"><span class="name"><i class="iconfont icon-date"></i>建站天数</span><span class="num"><?php echo $days; ?> 天</span></div><?php endif; ?></div></div>
    </div>
</aside>
